<?php

namespace Database\Seeders;

use App\Models\PaymentChannel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PaymentChannelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $channels = [
            [
                'code' => 'MYBVA',
                'name' => 'Maybank Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 15,
                'max_expired' => 43200,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'PERMATAVA',
                'name' => 'Permata Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 60,
                'max_expired' => 43200,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'BNIVA',
                'name' => 'BNI Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 15,
                'max_expired' => 1440,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'BRIVA',
                'name' => 'BRI Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 60,
                'max_expired' => 43200,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'MANDIRIVA',
                'name' => 'Mandiri Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 60,
                'max_expired' => 43200,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'BCAVA',
                'name' => 'BCA Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 15,
                'max_expired' => 43200,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 5500,
            ],
            [
                'code' => 'MUAMALATVA',
                'name' => 'Muamalat Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 60,
                'max_expired' => 180,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'CIMBVA',
                'name' => 'CIMB Niaga Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 15,
                'max_expired' => 43200,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'BSIVA',
                'name' => 'BSI Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 60,
                'max_expired' => 180,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'OCBCVA',
                'name' => 'OCBC NISP Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 15,
                'max_expired' => 43200,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'DANAMONVA',
                'name' => 'Danamon Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 15,
                'max_expired' => 43200,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'OTHERBANKVA',
                'name' => 'Other Bank Virtual Account',
                'min_amount' => 10000,
                'max_amount' => 10000000,
                'min_expired' => 15,
                'max_expired' => 1440,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 4250,
            ],
            [
                'code' => 'ALFAMART',
                'name' => 'Alfamart',
                'min_amount' => 10000,
                'max_amount' => 2500000,
                'min_expired' => 60,
                'max_expired' => 1440,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 3500,
            ],
            [
                'code' => 'INDOMARET',
                'name' => 'Indomaret',
                'min_amount' => 10000,
                'max_amount' => 2500000,
                'min_expired' => 15,
                'max_expired' => 43200,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 3500,
            ],
            [
                'code' => 'ALFAMIDI',
                'name' => 'Alfamidi',
                'min_amount' => 5000,
                'max_amount' => 2500000,
                'min_expired' => 60,
                'max_expired' => 1440,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 3500,
            ],
            [
                'code' => 'OVO',
                'name' => 'OVO',
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'min_expired' => 15,
                'max_expired' => 43200,
                'time_expired' => 'minute',
                'type' => 'redirect',
                'tax' => 0.03,
            ],
            [
                'code' => 'QRIS',
                'name' => 'QRIS by ShopeePay',
                'min_amount' => 1000,
                'max_amount' => 5000000,
                'min_expired' => 60,
                'max_expired' => 60,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 750,
            ],
            [
                'code' => 'QRISC',
                'name' => 'QRIS (Customizable)',
                'min_amount' => 1000,
                'max_amount' => 5000000,
                'min_expired' => 60,
                'max_expired' => 1440,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 750,
            ],
            [
                'code' => 'QRIS2',
                'name' => 'QRIS',
                'min_amount' => 1000,
                'max_amount' => 5000000,
                'min_expired' => 60,
                'max_expired' => 60,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 750,
            ],
            [
                'code' => 'DANA',
                'name' => 'DANA',
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'min_expired' => 15,
                'max_expired' => 1440,
                'time_expired' => 'minute',
                'type' => 'redirect',
                'tax' => 0.03,
            ],
            [
                'code' => 'SHOPEEPAY',
                'name' => 'ShopeePay',
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'min_expired' => 15,
                'max_expired' => 60,
                'time_expired' => 'minute',
                'type' => 'redirect',
                'tax' => 0.03,
            ],
            [
                'code' => 'QRIS_SHOPEEPAY',
                'name' => 'QRIS Custom by ShopeePay',
                'min_amount' => 1000,
                'max_amount' => 5000000,
                'min_expired' => 60,
                'max_expired' => 60,
                'time_expired' => 'minute',
                'type' => 'direct',
                'tax' => 750,
            ],
        ];

        foreach($channels as $channel){
            PaymentChannel::create($channel);
        }
    }
}
